"use client";
import { useState } from "react";
import { Button, DatePicker, Form, Input, InputNumber, message, Modal, Select, Space, Typography } from "antd";
import api from "../../../lib/api";
import { DataTable, errorText, requestId, Row } from "./common";
import { usePaged } from "./usePaged";

export default function CodeManagement() {
  const [filters, setFilters] = useState<Record<string, unknown>>({}); const data = usePaged("/commercial/codes", filters);
  const search = (v: Record<string, unknown>) => { const range = v.created_range as Array<{toISOString(): string}> | undefined; const next = {...v}; delete next.created_range; if (range?.length === 2) { next.created_from = range[0].toISOString(); next.created_to = range[1].toISOString(); } setFilters(next); };
  const create = () => { let values = { code_type: "group_license", agent_id: undefined as number | undefined, customer_id: undefined as number | undefined, value: 365, expires_hours: 168, max_uses: 1 };
    Modal.confirm({ title: "生成授权/兑换码", content: <Form layout="vertical" initialValues={values} onValuesChange={(_, all) => values = all}>
      <Form.Item name="code_type" label="类型"><Select options={["group_license", "diamonds", "membership", "partner_slot", "baby_slot"].map(value => ({ value }))} /></Form.Item>
      <Form.Item name="agent_id" label="代理 ID"><InputNumber min={1} /></Form.Item><Form.Item name="customer_id" label="预绑定客户 ID"><InputNumber min={1} /></Form.Item>
      <Form.Item name="value" label="数值"><InputNumber min={0} /></Form.Item><Form.Item name="expires_hours" label="有效小时"><InputNumber min={1} /></Form.Item><Form.Item name="max_uses" label="最大使用次数"><InputNumber min={1} max={1000} /></Form.Item>
    </Form>, async onOk() { try { const response = await api.post("/commercial/codes", { ...values, request_id: requestId() }); const code = response.data.code; Modal.info({ title: "完整码仅显示一次", content: <Typography.Text copyable strong>{code}</Typography.Text> }); await data.load(1); } catch (e) { message.error(errorText(e)); throw e; } } }); };
  const action = (r: Row, op: "freeze" | "unfreeze" | "void" | "refund") => { let reason = ""; Modal.confirm({ title: `确认 ${op}？`, content: <Input placeholder="操作原因" onChange={e => reason = e.target.value} />, async onOk() { try { const id = requestId(); await api.post(`/commercial/codes/${r.id}/${op}`, op === "refund" ? { reason, idempotency_key: id } : { reason, request_id: id }); message.success("操作成功"); await data.load(); } catch (e) { message.error(errorText(e)); throw e; } } }); };
  return <><Space><Button type="primary" onClick={create}>生成授权码</Button></Space>
    <Form layout="inline" onFinish={search}><Form.Item name="agent_id"><Input placeholder="代理ID" /></Form.Item><Form.Item name="customer_id"><Input placeholder="客户ID" /></Form.Item><Form.Item name="prefix"><Input placeholder="Prefix" /></Form.Item><Form.Item name="code_type"><Select allowClear placeholder="类型" style={{ width: 140 }} options={["group_license", "diamonds", "membership", "partner_slot", "baby_slot"].map(value => ({ value }))} /></Form.Item><Form.Item name="status"><Select allowClear placeholder="状态" style={{ width: 120 }} options={["active", "frozen", "void", "redeemed"].map(value => ({ value }))} /></Form.Item><Form.Item name="created_range"><DatePicker.RangePicker showTime /></Form.Item><Space><Button type="primary" htmlType="submit">搜索</Button><Button onClick={() => setFilters({})}>重置</Button></Space></Form>
    <DataTable {...data} onPage={data.load} onRefresh={() => data.load()} columns={[{ title: "ID", dataIndex: "id" }, { title: "Prefix", dataIndex: "code_prefix" }, { title: "类型", dataIndex: "code_type" }, { title: "代理/客户", render: (_, r) => `${r.agent_id ?? "-"} / ${r.customer_id ?? "-"}` }, { title: "状态", dataIndex: "status" }, { title: "使用", render: (_, r) => `${r.used_count}/${r.max_uses}` }, { title: "预留", dataIndex: "reserved_total" }, { title: "已用", dataIndex: "used_total" }, { title: "可退", dataIndex: "remaining_reserved" }, { title: "资金来源", dataIndex: "reservation_source" }, { title: "操作", render: (_, r) => <Space><Button disabled={!(["active", "frozen"].includes(String(r.status)))} onClick={() => action(r, r.status === "frozen" ? "unfreeze" : "freeze")}>{r.status === "frozen" ? "解冻" : "冻结"}</Button><Button danger disabled={!(["active", "frozen"].includes(String(r.status)))} onClick={() => action(r, "void")}>作废</Button><Button danger disabled={!(["frozen", "void"].includes(String(r.status))) || r.remaining_reserved == null} onClick={() => action(r, "refund")}>退额度</Button></Space> }]} />
  </>;
}
